// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AppSettingsInitParameters struct {

	// Number of parallel worker goroutines used for campaign sending. Maps to `app.concurrency`.
	Concurrency *float64 `json:"concurrency,omitempty" tf:"concurrency,omitempty"`

	// Public URL to a favicon used in the admin UI + subscriber pages. Maps to `app.favicon_url`.
	FaviconURL *string `json:"faviconUrl,omitempty" tf:"favicon_url,omitempty"`

	// Default From: address used when sending campaign mail. Maps to `app.from_email`.
	FromEmail *string `json:"fromEmail,omitempty" tf:"from_email,omitempty"`

	// Default UI language code (e.g. `en`, `de`, `fr`). Maps to `app.lang`.
	Lang *string `json:"lang,omitempty" tf:"lang,omitempty"`

	// Public URL to a logo image used in the admin UI + subscriber pages. Maps to `app.logo_url`.
	LogoURL *string `json:"logoUrl,omitempty" tf:"logo_url,omitempty"`

	// Max messages per second per concurrency worker. Maps to `app.message_rate`.
	MessageRate *float64 `json:"messageRate,omitempty" tf:"message_rate,omitempty"`

	// Public root URL Listmonk uses when constructing absolute links (subscription confirm, click-tracking, OIDC redirect URI). E.g. `https://marketing.example.com`. Maps to `app.root_url`.
	RootURL *string `json:"rootUrl,omitempty" tf:"root_url,omitempty"`

	// Brand name shown in the admin UI + subscriber-facing pages. Maps to `app.site_name`.
	SiteName *string `json:"siteName,omitempty" tf:"site_name,omitempty"`
}

type AppSettingsObservation struct {

	// Number of parallel worker goroutines used for campaign sending. Maps to `app.concurrency`.
	Concurrency *float64 `json:"concurrency,omitempty" tf:"concurrency,omitempty"`

	// Public URL to a favicon used in the admin UI + subscriber pages. Maps to `app.favicon_url`.
	FaviconURL *string `json:"faviconUrl,omitempty" tf:"favicon_url,omitempty"`

	// Default From: address used when sending campaign mail. Maps to `app.from_email`.
	FromEmail *string `json:"fromEmail,omitempty" tf:"from_email,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Default UI language code (e.g. `en`, `de`, `fr`). Maps to `app.lang`.
	Lang *string `json:"lang,omitempty" tf:"lang,omitempty"`

	// Public URL to a logo image used in the admin UI + subscriber pages. Maps to `app.logo_url`.
	LogoURL *string `json:"logoUrl,omitempty" tf:"logo_url,omitempty"`

	// Max messages per second per concurrency worker. Maps to `app.message_rate`.
	MessageRate *float64 `json:"messageRate,omitempty" tf:"message_rate,omitempty"`

	// Public root URL Listmonk uses when constructing absolute links (subscription confirm, click-tracking, OIDC redirect URI). E.g. `https://marketing.example.com`. Maps to `app.root_url`.
	RootURL *string `json:"rootUrl,omitempty" tf:"root_url,omitempty"`

	// Brand name shown in the admin UI + subscriber-facing pages. Maps to `app.site_name`.
	SiteName *string `json:"siteName,omitempty" tf:"site_name,omitempty"`
}

type AppSettingsParameters struct {

	// Number of parallel worker goroutines used for campaign sending. Maps to `app.concurrency`.
	// +kubebuilder:validation:Optional
	Concurrency *float64 `json:"concurrency,omitempty" tf:"concurrency,omitempty"`

	// Public URL to a favicon used in the admin UI + subscriber pages. Maps to `app.favicon_url`.
	// +kubebuilder:validation:Optional
	FaviconURL *string `json:"faviconUrl,omitempty" tf:"favicon_url,omitempty"`

	// Default From: address used when sending campaign mail. Maps to `app.from_email`.
	// +kubebuilder:validation:Optional
	FromEmail *string `json:"fromEmail,omitempty" tf:"from_email,omitempty"`

	// Default UI language code (e.g. `en`, `de`, `fr`). Maps to `app.lang`.
	// +kubebuilder:validation:Optional
	Lang *string `json:"lang,omitempty" tf:"lang,omitempty"`

	// Public URL to a logo image used in the admin UI + subscriber pages. Maps to `app.logo_url`.
	// +kubebuilder:validation:Optional
	LogoURL *string `json:"logoUrl,omitempty" tf:"logo_url,omitempty"`

	// Max messages per second per concurrency worker. Maps to `app.message_rate`.
	// +kubebuilder:validation:Optional
	MessageRate *float64 `json:"messageRate,omitempty" tf:"message_rate,omitempty"`

	// Public root URL Listmonk uses when constructing absolute links (subscription confirm, click-tracking, OIDC redirect URI). E.g. `https://marketing.example.com`. Maps to `app.root_url`.
	// +kubebuilder:validation:Optional
	RootURL *string `json:"rootUrl,omitempty" tf:"root_url,omitempty"`

	// Brand name shown in the admin UI + subscriber-facing pages. Maps to `app.site_name`.
	// +kubebuilder:validation:Optional
	SiteName *string `json:"siteName,omitempty" tf:"site_name,omitempty"`
}

// AppSettingsSpec defines the desired state of AppSettings
type AppSettingsSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AppSettingsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AppSettingsInitParameters `json:"initProvider,omitempty"`
}

// AppSettingsStatus defines the observed state of AppSettings.
type AppSettingsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AppSettingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AppSettings is the Schema for the AppSettingss API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,listmonk}
type AppSettings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AppSettingsSpec   `json:"spec"`
	Status            AppSettingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AppSettingsList contains a list of AppSettingss
type AppSettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AppSettings `json:"items"`
}

// Repository type metadata.
var (
	AppSettings_Kind             = "AppSettings"
	AppSettings_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AppSettings_Kind}.String()
	AppSettings_KindAPIVersion   = AppSettings_Kind + "." + CRDGroupVersion.String()
	AppSettings_GroupVersionKind = CRDGroupVersion.WithKind(AppSettings_Kind)
)

func init() {
	SchemeBuilder.Register(&AppSettings{}, &AppSettingsList{})
}
