// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type OidcInitParameters struct {

	// in by an unknown OIDC subject creates a Listmonk user assigned the role identified by default_user_role_id. Listmonk's OIDC subject-to-role mapping does not consume groups/roles claims — see the provider README for the explicit-allowlist alternative.
	// When true, sign-in by an unknown OIDC subject creates a Listmonk user assigned the role identified by `default_user_role_id`. Listmonk's OIDC subject-to-role mapping does not consume `groups`/`roles` claims — see the provider README for the explicit-allowlist alternative.
	AutoCreateUsers *bool `json:"autoCreateUsers,omitempty" tf:"auto_create_users,omitempty"`

	// (String) OIDC application client ID.
	// OIDC application client ID.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// only — Listmonk masks the value on read.
	// OIDC application client secret. Write-only — Listmonk masks the value on read.
	ClientSecretSecretRef *v1.LocalSecretKeySelector `json:"clientSecretSecretRef,omitempty" tf:"-"`

	// created users. Leave null to leave Listmonk's default in place.
	// List role ID assigned to auto-created users. Leave null to leave Listmonk's default in place.
	DefaultListRoleID *float64 `json:"defaultListRoleId,omitempty" tf:"default_list_role_id,omitempty"`

	// created users (typically a listmonk_user_role ID). Leave null to leave Listmonk's default in place.
	// User role ID assigned to auto-created users (typically a `listmonk_user_role` ID). Leave null to leave Listmonk's default in place.
	DefaultUserRoleID *float64 `json:"defaultUserRoleId,omitempty" tf:"default_user_role_id,omitempty"`

	// in.
	// Enable OIDC sign-in.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// in page (e.g. Zitadel).
	// Display name shown on the sign-in page (e.g. `Zitadel`).
	ProviderName *string `json:"providerName,omitempty" tf:"provider_name,omitempty"`

	// known/openid-configuration to discover endpoints.
	// OIDC issuer base URL (e.g. `https://auth.example.com`). Listmonk fetches `<provider_url>/.well-known/openid-configuration` to discover endpoints.
	ProviderURL *string `json:"providerUrl,omitempty" tf:"provider_url,omitempty"`
}

type OidcObservation struct {

	// in by an unknown OIDC subject creates a Listmonk user assigned the role identified by default_user_role_id. Listmonk's OIDC subject-to-role mapping does not consume groups/roles claims — see the provider README for the explicit-allowlist alternative.
	// When true, sign-in by an unknown OIDC subject creates a Listmonk user assigned the role identified by `default_user_role_id`. Listmonk's OIDC subject-to-role mapping does not consume `groups`/`roles` claims — see the provider README for the explicit-allowlist alternative.
	AutoCreateUsers *bool `json:"autoCreateUsers,omitempty" tf:"auto_create_users,omitempty"`

	// (String) OIDC application client ID.
	// OIDC application client ID.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// created users. Leave null to leave Listmonk's default in place.
	// List role ID assigned to auto-created users. Leave null to leave Listmonk's default in place.
	DefaultListRoleID *float64 `json:"defaultListRoleId,omitempty" tf:"default_list_role_id,omitempty"`

	// created users (typically a listmonk_user_role ID). Leave null to leave Listmonk's default in place.
	// User role ID assigned to auto-created users (typically a `listmonk_user_role` ID). Leave null to leave Listmonk's default in place.
	DefaultUserRoleID *float64 `json:"defaultUserRoleId,omitempty" tf:"default_user_role_id,omitempty"`

	// in.
	// Enable OIDC sign-in.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// in page (e.g. Zitadel).
	// Display name shown on the sign-in page (e.g. `Zitadel`).
	ProviderName *string `json:"providerName,omitempty" tf:"provider_name,omitempty"`

	// known/openid-configuration to discover endpoints.
	// OIDC issuer base URL (e.g. `https://auth.example.com`). Listmonk fetches `<provider_url>/.well-known/openid-configuration` to discover endpoints.
	ProviderURL *string `json:"providerUrl,omitempty" tf:"provider_url,omitempty"`
}

type OidcParameters struct {

	// in by an unknown OIDC subject creates a Listmonk user assigned the role identified by default_user_role_id. Listmonk's OIDC subject-to-role mapping does not consume groups/roles claims — see the provider README for the explicit-allowlist alternative.
	// When true, sign-in by an unknown OIDC subject creates a Listmonk user assigned the role identified by `default_user_role_id`. Listmonk's OIDC subject-to-role mapping does not consume `groups`/`roles` claims — see the provider README for the explicit-allowlist alternative.
	// +kubebuilder:validation:Optional
	AutoCreateUsers *bool `json:"autoCreateUsers,omitempty" tf:"auto_create_users,omitempty"`

	// (String) OIDC application client ID.
	// OIDC application client ID.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// only — Listmonk masks the value on read.
	// OIDC application client secret. Write-only — Listmonk masks the value on read.
	// +kubebuilder:validation:Optional
	ClientSecretSecretRef *v1.LocalSecretKeySelector `json:"clientSecretSecretRef,omitempty" tf:"-"`

	// created users. Leave null to leave Listmonk's default in place.
	// List role ID assigned to auto-created users. Leave null to leave Listmonk's default in place.
	// +kubebuilder:validation:Optional
	DefaultListRoleID *float64 `json:"defaultListRoleId,omitempty" tf:"default_list_role_id,omitempty"`

	// created users (typically a listmonk_user_role ID). Leave null to leave Listmonk's default in place.
	// User role ID assigned to auto-created users (typically a `listmonk_user_role` ID). Leave null to leave Listmonk's default in place.
	// +kubebuilder:validation:Optional
	DefaultUserRoleID *float64 `json:"defaultUserRoleId,omitempty" tf:"default_user_role_id,omitempty"`

	// in.
	// Enable OIDC sign-in.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// in page (e.g. Zitadel).
	// Display name shown on the sign-in page (e.g. `Zitadel`).
	// +kubebuilder:validation:Optional
	ProviderName *string `json:"providerName,omitempty" tf:"provider_name,omitempty"`

	// known/openid-configuration to discover endpoints.
	// OIDC issuer base URL (e.g. `https://auth.example.com`). Listmonk fetches `<provider_url>/.well-known/openid-configuration` to discover endpoints.
	// +kubebuilder:validation:Optional
	ProviderURL *string `json:"providerUrl,omitempty" tf:"provider_url,omitempty"`
}

type SecuritySettingsInitParameters struct {
}

type SecuritySettingsObservation struct {

	// (String) Synthetic ID for the singleton settings section. Always security.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// side OIDC settings. (see below for nested schema)
	// OpenID Connect SSO configuration (the `security.oidc` row). When this block is omitted the provider does not touch the server-side OIDC settings.
	Oidc []OidcObservation `json:"oidc,omitempty" tf:"oidc,omitempty"`
}

type SecuritySettingsParameters struct {
}

// SecuritySettingsSpec defines the desired state of SecuritySettings
type SecuritySettingsSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SecuritySettingsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SecuritySettingsInitParameters `json:"initProvider,omitempty"`
}

// SecuritySettingsStatus defines the observed state of SecuritySettings.
type SecuritySettingsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SecuritySettingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SecuritySettings is the Schema for the SecuritySettingss API. Listmonk Security settings — the security.* rows of the settings table. Singleton resource per Listmonk instance (one security section per server). v0.1 manages the security.oidc sub-block; future versions will add security.captcha and security.basic_auth. Drift behavior: only sub-blocks declared in this resource are reconciled. Operator UI edits to undeclared sub-blocks (e.g. CAPTCHA) are preserved. Client secret: Listmonk masks oidc. Rotate by changing the HCL value and applying.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,listmonk}
type SecuritySettings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SecuritySettingsSpec   `json:"spec"`
	Status            SecuritySettingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecuritySettingsList contains a list of SecuritySettingss
type SecuritySettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecuritySettings `json:"items"`
}

// Repository type metadata.
var (
	SecuritySettings_Kind             = "SecuritySettings"
	SecuritySettings_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SecuritySettings_Kind}.String()
	SecuritySettings_KindAPIVersion   = SecuritySettings_Kind + "." + CRDGroupVersion.String()
	SecuritySettings_GroupVersionKind = CRDGroupVersion.WithKind(SecuritySettings_Kind)
)

func init() {
	SchemeBuilder.Register(&SecuritySettings{}, &SecuritySettingsList{})
}
