// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type UserRoleInitParameters struct {

	// Human-readable role name. Shown in the Listmonk admin UI's role picker.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Set of dotted-string permissions granted by this role. See Listmonk's source for the canonical list (e.g. `settings:get`, `settings:manage`, `users:get`, `users:manage`, `roles:get`, `roles:manage`, `lists:get_all`, `lists:manage_all`, `templates:get`, `templates:manage`, `campaigns:get`, `campaigns:manage`, `subscribers:manage`, `bounces:get`, `bounces:manage`, `media:get`, `media:manage`, `tx:send`).
	// +listType=set
	Permissions []*string `json:"permissions,omitempty" tf:"permissions,omitempty"`
}

type UserRoleObservation struct {

	// RFC 3339 timestamp.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Human-readable role name. Shown in the Listmonk admin UI's role picker.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Set of dotted-string permissions granted by this role. See Listmonk's source for the canonical list (e.g. `settings:get`, `settings:manage`, `users:get`, `users:manage`, `roles:get`, `roles:manage`, `lists:get_all`, `lists:manage_all`, `templates:get`, `templates:manage`, `campaigns:get`, `campaigns:manage`, `subscribers:manage`, `bounces:get`, `bounces:manage`, `media:get`, `media:manage`, `tx:send`).
	// +listType=set
	Permissions []*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// RFC 3339 timestamp.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type UserRoleParameters struct {

	// Human-readable role name. Shown in the Listmonk admin UI's role picker.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Set of dotted-string permissions granted by this role. See Listmonk's source for the canonical list (e.g. `settings:get`, `settings:manage`, `users:get`, `users:manage`, `roles:get`, `roles:manage`, `lists:get_all`, `lists:manage_all`, `templates:get`, `templates:manage`, `campaigns:get`, `campaigns:manage`, `subscribers:manage`, `bounces:get`, `bounces:manage`, `media:get`, `media:manage`, `tx:send`).
	// +kubebuilder:validation:Optional
	// +listType=set
	Permissions []*string `json:"permissions,omitempty" tf:"permissions,omitempty"`
}

// UserRoleSpec defines the desired state of UserRole
type UserRoleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserRoleInitParameters `json:"initProvider,omitempty"`
}

// UserRoleStatus defines the observed state of UserRole.
type UserRoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UserRole is the Schema for the UserRoles API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,listmonk}
type UserRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.permissions) || (has(self.initProvider) && has(self.initProvider.permissions))",message="spec.forProvider.permissions is a required parameter"
	Spec   UserRoleSpec   `json:"spec"`
	Status UserRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserRoleList contains a list of UserRoles
type UserRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserRole `json:"items"`
}

// Repository type metadata.
var (
	UserRole_Kind             = "UserRole"
	UserRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserRole_Kind}.String()
	UserRole_KindAPIVersion   = UserRole_Kind + "." + CRDGroupVersion.String()
	UserRole_GroupVersionKind = CRDGroupVersion.WithKind(UserRole_Kind)
)

func init() {
	SchemeBuilder.Register(&UserRole{}, &UserRoleList{})
}
