// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type UserInitParameters struct {

	// Unique email address. For `api` users this doesn't need to be deliverable but must still be unique.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// Optional ID of a list role (`listmonk_list_role`) that defines this user's per-list access. Null leaves it unset.
	ListRoleID *float64 `json:"listRoleId,omitempty" tf:"list_role_id,omitempty"`

	// Display name shown in the Listmonk admin UI.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether this user can sign in via the Listmonk admin UI form. For `api` users set false. For `user` users typically true.
	PasswordLogin *bool `json:"passwordLogin,omitempty" tf:"password_login,omitempty"`

	// For `type = api`: the plaintext token used for HTTP Basic-Auth. For `type = user`: the operator-chosen password (Listmonk stores it bcrypt-hashed; never returned on Read so drift on it is undetectable — rotate by changing the HCL value and applying).
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// Lifecycle status: `enabled` or `disabled`. Disabled users can't authenticate but their row is preserved.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// User type: `user` (interactive) or `api` (machine credential whose `password` is the plaintext Basic-Auth token).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// ID of the user role (`listmonk_user_role`) that defines this user's permissions. Use `1` for the Listmonk-seeded `Super Admin` role.
	// +crossplane:generate:reference:type=github.com/hops-ops/provider-listmonk/apis/cluster/identity/v1alpha1.UserRole
	UserRoleID *float64 `json:"userRoleId,omitempty" tf:"user_role_id,omitempty"`

	// Reference to a UserRole in identity to populate userRoleId.
	// +kubebuilder:validation:Optional
	UserRoleIDRef *v1.Reference `json:"userRoleIdRef,omitempty" tf:"-"`

	// Selector for a UserRole in identity to populate userRoleId.
	// +kubebuilder:validation:Optional
	UserRoleIDSelector *v1.Selector `json:"userRoleIdSelector,omitempty" tf:"-"`

	// Unique username. Becomes the principal name for Basic-Auth on `api` users; the display name in the Listmonk admin UI for `user` users.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UserObservation struct {

	// RFC 3339 timestamp.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Unique email address. For `api` users this doesn't need to be deliverable but must still be unique.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Optional ID of a list role (`listmonk_list_role`) that defines this user's per-list access. Null leaves it unset.
	ListRoleID *float64 `json:"listRoleId,omitempty" tf:"list_role_id,omitempty"`

	// Display name shown in the Listmonk admin UI.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether this user can sign in via the Listmonk admin UI form. For `api` users set false. For `user` users typically true.
	PasswordLogin *bool `json:"passwordLogin,omitempty" tf:"password_login,omitempty"`

	// Lifecycle status: `enabled` or `disabled`. Disabled users can't authenticate but their row is preserved.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// User type: `user` (interactive) or `api` (machine credential whose `password` is the plaintext Basic-Auth token).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// RFC 3339 timestamp.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// ID of the user role (`listmonk_user_role`) that defines this user's permissions. Use `1` for the Listmonk-seeded `Super Admin` role.
	UserRoleID *float64 `json:"userRoleId,omitempty" tf:"user_role_id,omitempty"`

	// Unique username. Becomes the principal name for Basic-Auth on `api` users; the display name in the Listmonk admin UI for `user` users.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UserParameters struct {

	// Unique email address. For `api` users this doesn't need to be deliverable but must still be unique.
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// Optional ID of a list role (`listmonk_list_role`) that defines this user's per-list access. Null leaves it unset.
	// +kubebuilder:validation:Optional
	ListRoleID *float64 `json:"listRoleId,omitempty" tf:"list_role_id,omitempty"`

	// Display name shown in the Listmonk admin UI.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether this user can sign in via the Listmonk admin UI form. For `api` users set false. For `user` users typically true.
	// +kubebuilder:validation:Optional
	PasswordLogin *bool `json:"passwordLogin,omitempty" tf:"password_login,omitempty"`

	// For `type = api`: the plaintext token used for HTTP Basic-Auth. For `type = user`: the operator-chosen password (Listmonk stores it bcrypt-hashed; never returned on Read so drift on it is undetectable — rotate by changing the HCL value and applying).
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// Lifecycle status: `enabled` or `disabled`. Disabled users can't authenticate but their row is preserved.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// User type: `user` (interactive) or `api` (machine credential whose `password` is the plaintext Basic-Auth token).
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// ID of the user role (`listmonk_user_role`) that defines this user's permissions. Use `1` for the Listmonk-seeded `Super Admin` role.
	// +crossplane:generate:reference:type=github.com/hops-ops/provider-listmonk/apis/cluster/identity/v1alpha1.UserRole
	// +kubebuilder:validation:Optional
	UserRoleID *float64 `json:"userRoleId,omitempty" tf:"user_role_id,omitempty"`

	// Reference to a UserRole in identity to populate userRoleId.
	// +kubebuilder:validation:Optional
	UserRoleIDRef *v1.Reference `json:"userRoleIdRef,omitempty" tf:"-"`

	// Selector for a UserRole in identity to populate userRoleId.
	// +kubebuilder:validation:Optional
	UserRoleIDSelector *v1.Selector `json:"userRoleIdSelector,omitempty" tf:"-"`

	// Unique username. Becomes the principal name for Basic-Auth on `api` users; the display name in the Listmonk admin UI for `user` users.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// UserSpec defines the desired state of User
type UserSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserInitParameters `json:"initProvider,omitempty"`
}

// UserStatus defines the observed state of User.
type UserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// User is the Schema for the Users API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,listmonk}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.email) || (has(self.initProvider) && has(self.initProvider.email))",message="spec.forProvider.email is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordLogin) || (has(self.initProvider) && has(self.initProvider.passwordLogin))",message="spec.forProvider.passwordLogin is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.status) || (has(self.initProvider) && has(self.initProvider.status))",message="spec.forProvider.status is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   UserSpec   `json:"spec"`
	Status UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of Users
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// Repository type metadata.
var (
	User_Kind             = "User"
	User_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: User_Kind}.String()
	User_KindAPIVersion   = User_Kind + "." + CRDGroupVersion.String()
	User_GroupVersionKind = CRDGroupVersion.WithKind(User_Kind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
